# 打开debug信息显示
logging:
  level:
    web: debug
## mybatis-plus 相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  typeAliasesPackage: com.lsl.demo.*.*.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#我是redis啊
  redis:
    # ip
    host: 47.115.126.5
    # 密码
    password: 1998

